version: '3.6'
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${postgres_password}
#    healthcheck:
#        test: ["CMD", "curl", "-f", "http://localhost:5498"]
#        interval: 1m30s
#        timeout: 10s
#        retries: 3
  web:
    build: app
    #init: True # version 3.7+ only
    restart: on-failure
    ports:
      - "9898:9898"
    environment:
      - POSTGRES_PASSWORD=${postgres_password}
    depends_on:
      - db
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5000"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        
volumes:
  db-volume:
